// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'As DefaultFirebaseOptions não foram configuradas para o Windows - '
          'você pode reconfigurar isso executando novamente o FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'As DefaultFirebaseOptions não foram configuradas para o Linux - '
          'você pode reconfigurar isso executando novamente o FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'As DefaultFirebaseOptions não são suportadas para esta plataforma.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACHSZ3amgvdt_PChDVo5_OUfsYnwh_ZhY',
    appId: '1:1039846594044:web:272ca7d9ea41b1c7d64e79',
    messagingSenderId: '1039846594044',
    projectId: 'gccontrol-9683f',
    authDomain: 'gccontrol-9683f.firebaseapp.com',
    storageBucket: 'gccontrol-9683f.appspot.com',
    measurementId: 'G-BKCHXVTQWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHu_sRsl622bDS3aNEO5JHX9l_UXDsaE',
    appId: '1:1039846594044:android:9707b54766891bc1d64e79',
    messagingSenderId: '1039846594044',
    projectId: 'gccontrol-9683f',
    storageBucket: 'gccontrol-9683f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOm8EbRu4kFStUIBSjZ0CbBhsT9kpQPc',
    appId: '1:1039846594044:ios:2b1d2f079eb20a82d64e79',
    messagingSenderId: '1039846594044',
    projectId: 'gccontrol-9683f',
    storageBucket: 'gccontrol-9683f.appspot.com',
    iosBundleId: 'app.gccontrol.gccontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFOm8EbRu4kFStUIBSjZ0CbBhsT9kpQPc',
    appId: '1:1039846594044:ios:947c54476c2ecf20d64e79',
    messagingSenderId: '1039846594044',
    projectId: 'gccontrol-9683f',
    storageBucket: 'gccontrol-9683f.appspot.com',
    iosBundleId: 'app.gccontrol.gccontrol.RunnerTests',
  );
}
